# Generated by Django 3.0.6 on 2020-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200530_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ansewer',
        ),
        migrations.AddField(
            model_name='question',
            name='writer',
            field=models.CharField(default='', max_length=10),
        ),
    ]
