# Generated by Django 3.0.6 on 2020-05-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
