# Generated by Django 3.0.6 on 2020-06-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_answer_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_id',
            field=models.IntegerField(default=0),
        ),
    ]
