# Generated by Django 3.0.6 on 2020-06-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_answer_answer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_id',
        ),
    ]
