# Generated by Django 3.0.6 on 2020-05-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='pub_date',
        ),
    ]
