# Generated by Django 3.0.6 on 2020-06-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_auto_20200531_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='title',
            new_name='question',
        ),
    ]
